repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1 # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/klen/pylama
    rev: 8.4.1
    hooks:
      - id: pylama
#  - repo: local
#    hooks:
#      - id: tests
#        name: run tests
#        entry: sh -c 'pytest --no-migrations -v'
#        language: system
#        types: [python]
#        stages: [push]
